/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CheckRequestTupleKey
 */
public class CheckRequestTupleKeyTest {
    private final CheckRequestTupleKey model = new CheckRequestTupleKey();

    /**
     * Model tests for CheckRequestTupleKey
     */
    @Test
    public void testCheckRequestTupleKey() {
        // TODO: test CheckRequestTupleKey
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'relation'
     */
    @Test
    public void relationTest() {
        // TODO: test relation
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }
}
