/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ConditionParamTypeRef
 */
public class ConditionParamTypeRefTest {
    private final ConditionParamTypeRef model = new ConditionParamTypeRef();

    /**
     * Model tests for ConditionParamTypeRef
     */
    @Test
    public void testConditionParamTypeRef() {
        // TODO: test ConditionParamTypeRef
    }

    /**
     * Test the property 'typeName'
     */
    @Test
    public void typeNameTest() {
        // TODO: test typeName
    }

    /**
     * Test the property 'genericTypes'
     */
    @Test
    public void genericTypesTest() {
        // TODO: test genericTypes
    }
}
