/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for InternalErrorMessageResponse
 */
public class InternalErrorMessageResponseTest {
    private final InternalErrorMessageResponse model = new InternalErrorMessageResponse();

    /**
     * Model tests for InternalErrorMessageResponse
     */
    @Test
    public void testInternalErrorMessageResponse() {
        // TODO: test InternalErrorMessageResponse
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }
}
