/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Leaf
 */
public class LeafTest {
    private final Leaf model = new Leaf();

    /**
     * Model tests for Leaf
     */
    @Test
    public void testLeaf() {
        // TODO: test Leaf
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

    /**
     * Test the property 'computed'
     */
    @Test
    public void computedTest() {
        // TODO: test computed
    }

    /**
     * Test the property 'tupleToUserset'
     */
    @Test
    public void tupleToUsersetTest() {
        // TODO: test tupleToUserset
    }
}
