/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Metadata
 */
public class MetadataTest {
    private final Metadata model = new Metadata();

    /**
     * Model tests for Metadata
     */
    @Test
    public void testMetadata() {
        // TODO: test Metadata
    }

    /**
     * Test the property 'relations'
     */
    @Test
    public void relationsTest() {
        // TODO: test relations
    }
}
