/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Node
 */
public class NodeTest {
    private final Node model = new Node();

    /**
     * Model tests for Node
     */
    @Test
    public void testNode() {
        // TODO: test Node
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'leaf'
     */
    @Test
    public void leafTest() {
        // TODO: test leaf
    }

    /**
     * Test the property 'difference'
     */
    @Test
    public void differenceTest() {
        // TODO: test difference
    }

    /**
     * Test the property 'union'
     */
    @Test
    public void unionTest() {
        // TODO: test union
    }

    /**
     * Test the property 'intersection'
     */
    @Test
    public void intersectionTest() {
        // TODO: test intersection
    }
}
