/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ReadRequest
 */
public class ReadRequestTest {
    private final ReadRequest model = new ReadRequest();

    /**
     * Model tests for ReadRequest
     */
    @Test
    public void testReadRequest() {
        // TODO: test ReadRequest
    }

    /**
     * Test the property 'tupleKey'
     */
    @Test
    public void tupleKeyTest() {
        // TODO: test tupleKey
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'continuationToken'
     */
    @Test
    public void continuationTokenTest() {
        // TODO: test continuationToken
    }
}
