/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TupleChange
 */
public class TupleChangeTest {
    private final TupleChange model = new TupleChange();

    /**
     * Model tests for TupleChange
     */
    @Test
    public void testTupleChange() {
        // TODO: test TupleChange
    }

    /**
     * Test the property 'tupleKey'
     */
    @Test
    public void tupleKeyTest() {
        // TODO: test tupleKey
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }
}
