/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for UsersetTree
 */
public class UsersetTreeTest {
    private final UsersetTree model = new UsersetTree();

    /**
     * Model tests for UsersetTree
     */
    @Test
    public void testUsersetTree() {
        // TODO: test UsersetTree
    }

    /**
     * Test the property 'root'
     */
    @Test
    public void rootTest() {
        // TODO: test root
    }
}
