/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for UsersetTreeDifference
 */
public class UsersetTreeDifferenceTest {
    private final UsersetTreeDifference model = new UsersetTreeDifference();

    /**
     * Model tests for UsersetTreeDifference
     */
    @Test
    public void testUsersetTreeDifference() {
        // TODO: test UsersetTreeDifference
    }

    /**
     * Test the property 'base'
     */
    @Test
    public void baseTest() {
        // TODO: test base
    }

    /**
     * Test the property 'subtract'
     */
    @Test
    public void subtractTest() {
        // TODO: test subtract
    }
}
