/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.util;

import java.util.function.Predicate;
import java.util.regex.Pattern;

public class StringUtil {
    private StringUtil() {} // Instantiation prevented for utility class.

    private static final Predicate<String> NULL_OR_WS =
            Pattern.compile("^\\s*$").asMatchPredicate();

    /**
     * Returns true when the String is null, empty or contains only whitespace
     * characters.
     *
     * @param str The String being tested.
     * @return true iff str is null, empty or contains only whitespace.
     */
    public static boolean isNullOrWhitespace(String str) {
        return str == null || NULL_OR_WS.test(str);
    }
}
