/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.auth;

import static dev.openfga.sdk.util.StringUtil.isNullOrWhitespace;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

class AccessToken {
    private static final int TOKEN_EXPIRY_BUFFER_THRESHOLD_IN_SEC = 300;
    private Instant expiresAt;

    private String token;

    public boolean isValid() {
        if (isNullOrWhitespace(token) || expiresAt == null) {
            return false;
        }

        // A token should be considered valid until 5 minutes before the expiry
        Instant nowWithLeeway =
                Instant.now().plusSeconds(TOKEN_EXPIRY_BUFFER_THRESHOLD_IN_SEC).truncatedTo(ChronoUnit.SECONDS);

        return expiresAt.isAfter(nowWithLeeway);
    }

    public String getToken() {
        return token;
    }

    public void setExpiresAt(Instant expiresAt) {
        if (expiresAt != null) {
            // Truncate to seconds to zero out the milliseconds to keep comparison simpler
            this.expiresAt = expiresAt.truncatedTo(ChronoUnit.SECONDS);
        }
    }

    public void setToken(String token) {
        this.token = token;
    }
}
