/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api;

import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.pgssoft.httpclient.HttpClientMock;
import dev.openfga.sdk.api.client.*;
import dev.openfga.sdk.api.model.*;
import dev.openfga.sdk.errors.*;
import java.time.Duration;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * API tests for OpenFgaApi
 */
public class OpenFgaApiTest {
    private static final String DEFAULT_STORE_ID = "01YCP46JKYM8FJCQ37NMBYHE5X";
    private static final String DEFAULT_STORE_NAME = "test_store";
    private static final String DEFAULT_AUTH_MODEL_ID = "01G5JAVJ41T49E9TT3SKVS7X1J";
    private static final String DEFAULT_USER = "user:81684243-9356-4421-8fbf-a4f8d36aa31b";
    private static final String DEFAULT_RELATION = "reader";
    private static final String DEFAULT_TYPE = "document";
    private static final String DEFAULT_OBJECT = "document:budget";
    private static final String DEFAULT_SCHEMA_VERSION = "1.1";
    public static final String EMPTY_RESPONSE_BODY = "{}";

    private final ObjectMapper mapper = new ObjectMapper();
    private OpenFgaApi fga;
    private Configuration mockConfiguration;
    private ApiClient mockApiClient;
    private HttpClientMock mockHttpClient;

    @BeforeEach
    public void beforeEachTest() {
        mockHttpClient = new HttpClientMock();

        mockConfiguration = mock(Configuration.class);
        when(mockConfiguration.getApiUrl()).thenReturn("https://localhost");
        when(mockConfiguration.getReadTimeout()).thenReturn(Duration.ofMillis(250));

        mockApiClient = mock(ApiClient.class);
        when(mockApiClient.getObjectMapper()).thenReturn(mapper);
        when(mockApiClient.getHttpClient()).thenReturn(mockHttpClient);

        fga = new OpenFgaApi(mockApiClient, mockConfiguration);
    }

    /**
     * List all stores.
     */
    @Test
    public void listStoresTest() throws ApiException {
        // Given
        String responseBody =
                String.format("{\"stores\":[{\"id\":\"%s\",\"name\":\"%s\"}]}", DEFAULT_STORE_ID, DEFAULT_STORE_NAME);
        mockHttpClient.onGet("https://localhost/stores").doReturn(200, responseBody);
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ListStoresResponse response = fga.listStores(pageSize, continuationToken);

        // Then
        mockHttpClient.verify().get("https://localhost/stores").called(1);
        assertNotNull(response.getStores());
        assertEquals(1, response.getStores().size());
        assertEquals(DEFAULT_STORE_ID, response.getStores().get(0).getId());
        assertEquals(DEFAULT_STORE_NAME, response.getStores().get(0).getName());
    }

    @Test
    public void listStores_400() throws ApiException {
        // Given
        mockHttpClient
                .onGet("https://localhost/stores")
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.listStores(pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get("https://localhost/stores").called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void listStores_404() throws ApiException {
        // Given
        mockHttpClient
                .onGet("https://localhost/stores")
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.listStores(pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get("https://localhost/stores").called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void listStores_500() throws ApiException {
        // Given
        mockHttpClient
                .onGet("https://localhost/stores")
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.listStores(pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get("https://localhost/stores").called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Create a store.
     */
    @Test
    public void createStoreTest() throws ApiException {
        // Given
        String expectedBody = String.format("{\"name\":\"%s\"}", DEFAULT_STORE_NAME);
        String requestBody = String.format("{\"id\":\"%s\",\"name\":\"%s\"}", DEFAULT_STORE_ID, DEFAULT_STORE_NAME);
        mockHttpClient
                .onPost("https://localhost/stores")
                .withBody(is(expectedBody))
                .doReturn(201, requestBody);
        CreateStoreRequest request = new CreateStoreRequest().name(DEFAULT_STORE_NAME);

        // When
        CreateStoreResponse response = fga.createStore(request);

        // Then
        mockHttpClient
                .verify()
                .post("https://localhost/stores")
                .withBody(is(expectedBody))
                .called(1);
        assertEquals(DEFAULT_STORE_ID, response.getId());
        assertEquals(DEFAULT_STORE_NAME, response.getName());
    }

    @Test
    public void createStore_bodyRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.createStore(null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling createStore", exception.getMessage());
    }

    @Test
    public void createStore_400() throws ApiException {
        // Given
        mockHttpClient
                .onPost("https://localhost/stores")
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.createStore(new CreateStoreRequest()));

        // Then
        mockHttpClient.verify().post("https://localhost/stores").called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void createStore_404() throws ApiException {
        // Given
        mockHttpClient
                .onPost("https://localhost/stores")
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.createStore(new CreateStoreRequest()));

        // Then
        mockHttpClient.verify().post("https://localhost/stores").called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void createStore_500() throws ApiException {
        // Given
        mockHttpClient
                .onPost("https://localhost/stores")
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.createStore(new CreateStoreRequest()));

        // Then
        mockHttpClient.verify().post("https://localhost/stores").called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Get a store.
     */
    @Test
    public void getStoreTest() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        String responseBody = String.format("{\"id\":\"%s\",\"name\":\"%s\"}", DEFAULT_STORE_ID, DEFAULT_STORE_NAME);
        mockHttpClient.onGet(getUrl).doReturn(200, responseBody);

        // When
        GetStoreResponse response = fga.getStore(DEFAULT_STORE_ID);

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(DEFAULT_STORE_ID, response.getId());
        assertEquals(DEFAULT_STORE_NAME, response.getName());
    }

    @Test
    public void getStore_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.getStore(null));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling getStore", exception.getMessage());
    }

    @Test
    public void getStore_400() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.getStore(DEFAULT_STORE_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void getStore_404() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.getStore(DEFAULT_STORE_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void getStore_500() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.getStore(DEFAULT_STORE_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Delete a store.
     */
    @Test
    public void deleteStoreTest() throws ApiException {
        // Given
        String deleteUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient.onDelete(deleteUrl).doReturn(204, EMPTY_RESPONSE_BODY);

        // When
        fga.deleteStore(DEFAULT_STORE_ID);

        // Then
        mockHttpClient.verify().delete(deleteUrl).called(1);
    }

    @Test
    public void deleteStore_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.deleteStore(null));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling deleteStore", exception.getMessage());
    }

    @Test
    public void deleteStore_400() throws ApiException {
        // Given
        String deleteUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient
                .onDelete(deleteUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.deleteStore(DEFAULT_STORE_ID));

        // Then
        mockHttpClient.verify().delete(deleteUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void deleteStore_404() throws ApiException {
        // Given
        String deleteUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient
                .onDelete(deleteUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.deleteStore(DEFAULT_STORE_ID));

        // Then
        mockHttpClient.verify().delete(deleteUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void deleteStore_500() throws ApiException {
        // Given
        String deleteUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X";
        mockHttpClient
                .onDelete(deleteUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.deleteStore(DEFAULT_STORE_ID));

        // Then
        mockHttpClient.verify().delete(deleteUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Return all the authorization models for a particular store.
     */
    @Test
    public void readAuthorizationModelsTest() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        String responseBody = String.format(
                "{\"authorization_models\":[{\"id\":\"%s\",\"schema_version\":\"%s\"}]}",
                DEFAULT_AUTH_MODEL_ID, DEFAULT_SCHEMA_VERSION);
        mockHttpClient.onGet(getUrl).doReturn(200, responseBody);
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ReadAuthorizationModelsResponse response =
                fga.readAuthorizationModels(DEFAULT_STORE_ID, pageSize, continuationToken);

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertNotNull(response.getAuthorizationModels());
        assertEquals(1, response.getAuthorizationModels().size());
        AuthorizationModel authModel = response.getAuthorizationModels().get(0);
        assertEquals(DEFAULT_AUTH_MODEL_ID, authModel.getId());
        assertEquals(DEFAULT_SCHEMA_VERSION, authModel.getSchemaVersion());
    }

    @Test
    public void readAuthorizationModels_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.readAuthorizationModels(null, null, null));

        // Then
        assertEquals(
                "Missing the required parameter 'storeId' when calling readAuthorizationModels",
                exception.getMessage());
    }

    @Test
    public void readAuthorizationModels_400() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readAuthorizationModels(DEFAULT_STORE_ID, pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void readAuthorizationModels_404() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readAuthorizationModels(DEFAULT_STORE_ID, pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void readAuthorizationModels_500() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readAuthorizationModels(DEFAULT_STORE_ID, pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Create a new authorization model.
     */
    @Test
    public void writeAuthorizationModelTest() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        String expectedBody =
                "{\"type_definitions\":[{\"type\":\"document\",\"relations\":{},\"metadata\":null}],\"schema_version\":\"1.1\"}";
        String responseBody = String.format("{\"authorization_model_id\":\"%s\"}", DEFAULT_AUTH_MODEL_ID);
        mockHttpClient.onPost(postUrl).withBody(is(expectedBody)).doReturn(201, responseBody);
        WriteAuthorizationModelRequest request = new WriteAuthorizationModelRequest()
                .schemaVersion(DEFAULT_SCHEMA_VERSION)
                .typeDefinitions(List.of(new TypeDefinition().type(DEFAULT_TYPE)));

        // When
        WriteAuthorizationModelResponse response = fga.writeAuthorizationModel(DEFAULT_STORE_ID, request);

        // Then
        mockHttpClient.verify().post(postUrl).withBody(is(expectedBody)).called(1);
        assertEquals(DEFAULT_AUTH_MODEL_ID, response.getAuthorizationModelId());
    }

    @Test
    public void writeAuthorizationModel_storeIdRequired() {
        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.writeAuthorizationModel(null, new WriteAuthorizationModelRequest()));

        // Then
        assertEquals(
                "Missing the required parameter 'storeId' when calling writeAuthorizationModel",
                exception.getMessage());
    }

    @Test
    public void writeAuthorizationModel_bodyRequired() {
        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.writeAuthorizationModel(DEFAULT_STORE_ID, null));

        // Then
        assertEquals(
                "Missing the required parameter 'body' when calling writeAuthorizationModel", exception.getMessage());
    }

    @Test
    public void writeAuthorizationModel_400() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAuthorizationModel(DEFAULT_STORE_ID, new WriteAuthorizationModelRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void writeAuthorizationModel_404() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAuthorizationModel(DEFAULT_STORE_ID, new WriteAuthorizationModelRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void writeAuthorizationModel_500() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAuthorizationModel(DEFAULT_STORE_ID, new WriteAuthorizationModelRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Return a particular version of an authorization model.
     */
    @Test
    public void readAuthorizationModelTest() throws ApiException {
        // Given
        String getUrl =
                "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models/01G5JAVJ41T49E9TT3SKVS7X1J";
        String getResponse = String.format(
                "{\"authorization_model\":{\"id\":\"%s\",\"schema_version\":\"%s\"}}",
                DEFAULT_AUTH_MODEL_ID, DEFAULT_SCHEMA_VERSION);
        mockHttpClient.onGet(getUrl).doReturn(200, getResponse);

        // When
        ReadAuthorizationModelResponse response = fga.readAuthorizationModel(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID);

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertNotNull(response.getAuthorizationModel());
        assertEquals(DEFAULT_AUTH_MODEL_ID, response.getAuthorizationModel().getId());
        assertEquals(DEFAULT_SCHEMA_VERSION, response.getAuthorizationModel().getSchemaVersion());
    }

    @Test
    public void readAuthorizationModel_storeIdRequired() {
        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.readAuthorizationModel(null, DEFAULT_AUTH_MODEL_ID));

        // Then
        assertEquals(
                "Missing the required parameter 'storeId' when calling readAuthorizationModel", exception.getMessage());
    }

    @Test
    public void readAuthorizationModel_idRequired() {
        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.readAuthorizationModel(DEFAULT_STORE_ID, null));

        // Then
        assertEquals("Missing the required parameter 'id' when calling readAuthorizationModel", exception.getMessage());
    }

    @Test
    public void readAuthorizationModel_400() throws ApiException {
        // Given
        String getUrl =
                "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readAuthorizationModel(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void readAuthorizationModel_404() throws ApiException {
        // Given
        String getUrl =
                "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readAuthorizationModel(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void readAuthorizationModel_500() throws ApiException {
        // Given
        String getUrl =
                "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/authorization-models/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readAuthorizationModel(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Return a list of all the tuple changes.
     */
    @Test
    public void readChangesTest() throws ApiException {
        // Given
        String getPath = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/changes";
        String responseBody = String.format(
                "{\"changes\":[{\"tuple_key\":{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"}}]}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER);
        mockHttpClient.onGet(getPath).doReturn(200, responseBody);
        String type = null; // Input is optional
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ReadChangesResponse response = fga.readChanges(DEFAULT_STORE_ID, type, pageSize, continuationToken);

        // Then
        mockHttpClient.verify().get(getPath).called(1);
        assertNotNull(response.getChanges());
        assertEquals(1, response.getChanges().size());
        TupleChange change = response.getChanges().get(0);
        assertNotNull(change.getTupleKey());
        assertEquals(DEFAULT_OBJECT, change.getTupleKey().getObject());
        assertEquals(DEFAULT_RELATION, change.getTupleKey().getRelation());
        assertEquals(DEFAULT_USER, change.getTupleKey().getUser());
    }

    @Test
    public void readChanges_storeIdRequired() throws ApiException {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.readChanges(null, null, null, null));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling readChanges", exception.getMessage());
    }

    @Test
    public void readChanges_400() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/changes";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");
        String type = null; // Input is optional
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readChanges(DEFAULT_STORE_ID, type, pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void readChanges_404() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/changes";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");
        String type = null; // Input is optional
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readChanges(DEFAULT_STORE_ID, type, pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void readChanges_500() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/changes";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");
        String type = null; // Input is optional
        Integer pageSize = null; // Input is optional
        String continuationToken = null; // Input is optional

        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.readChanges(DEFAULT_STORE_ID, type, pageSize, continuationToken));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Get tuples from the store that matches a query, without following userset rewrite rules.
     */
    @Test
    public void readTest() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/read";
        String expectedBody = String.format(
                "{\"tuple_key\":{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"},\"page_size\":null,\"continuation_token\":null}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER);
        String responseBody = String.format(
                "{\"tuples\":[{\"key\":{\"user\":\"%s\",\"relation\":\"%s\",\"object\":\"%s\"}}]}",
                DEFAULT_USER, DEFAULT_RELATION, DEFAULT_OBJECT);
        mockHttpClient.onPost(postUrl).withBody(is(expectedBody)).doReturn(200, responseBody);
        ReadRequest request = new ReadRequest()
                .tupleKey(new TupleKey()
                        ._object(DEFAULT_OBJECT)
                        .relation(DEFAULT_RELATION)
                        .user(DEFAULT_USER));

        // When
        ReadResponse response = fga.read(DEFAULT_STORE_ID, request);

        // Then
        mockHttpClient.verify().post(postUrl).withBody(is(expectedBody)).called(1);
        assertNotNull(response.getTuples());
        assertEquals(1, response.getTuples().size());
        TupleKey key = response.getTuples().get(0).getKey();
        assertNotNull(key);
        assertEquals(DEFAULT_USER, key.getUser());
        assertEquals(DEFAULT_RELATION, key.getRelation());
        assertEquals(DEFAULT_OBJECT, key.getObject());
    }

    @Test
    public void read_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.read(null, new ReadRequest()));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling read", exception.getMessage());
    }

    @Test
    public void read_bodyRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.read(DEFAULT_STORE_ID, null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling read", exception.getMessage());
    }

    @Test
    public void read_400() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/read";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.read(DEFAULT_STORE_ID, new ReadRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void read_404() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/read";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.read(DEFAULT_STORE_ID, new ReadRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void read_500() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/read";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.read(DEFAULT_STORE_ID, new ReadRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Add or delete tuples from the store.
     */
    @Test
    public void writeTest_writes() throws ApiException {
        // Given
        String postPath = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/write";
        String expectedBody = String.format(
                "{\"writes\":{\"tuple_keys\":[{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"}]},\"deletes\":null,\"authorization_model_id\":\"%s\"}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER, DEFAULT_AUTH_MODEL_ID);
        mockHttpClient.onPost(postPath).withBody(is(expectedBody)).doReturn(200, EMPTY_RESPONSE_BODY);
        WriteRequest request = new WriteRequest()
                .authorizationModelId(DEFAULT_AUTH_MODEL_ID)
                .writes(new TupleKeys()
                        .tupleKeys(List.of(new TupleKey()
                                ._object(DEFAULT_OBJECT)
                                .relation(DEFAULT_RELATION)
                                .user(DEFAULT_USER))));

        // When
        fga.write(DEFAULT_STORE_ID, request);

        // Then
        mockHttpClient.verify().post(postPath).withBody(is(expectedBody)).called(1);
    }

    /**
     * Add or delete tuples from the store.
     */
    @Test
    public void writeTest_deletes() throws ApiException {
        // Given
        String postPath = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/write";
        String expectedBody = String.format(
                "{\"writes\":null,\"deletes\":{\"tuple_keys\":[{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"}]},\"authorization_model_id\":\"%s\"}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER, DEFAULT_AUTH_MODEL_ID);
        mockHttpClient.onPost(postPath).withBody(is(expectedBody)).doReturn(200, EMPTY_RESPONSE_BODY);
        WriteRequest request = new WriteRequest()
                .authorizationModelId(DEFAULT_AUTH_MODEL_ID)
                .deletes(new TupleKeys()
                        .tupleKeys(List.of(new TupleKey()
                                ._object(DEFAULT_OBJECT)
                                .relation(DEFAULT_RELATION)
                                .user(DEFAULT_USER))));

        // When
        fga.write(DEFAULT_STORE_ID, request);

        // Then
        mockHttpClient.verify().post(postPath).withBody(is(expectedBody)).called(1);
    }

    @Test
    public void write_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.write(null, new WriteRequest()));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling write", exception.getMessage());
    }

    @Test
    public void write_bodyRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.write(DEFAULT_STORE_ID, null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling write", exception.getMessage());
    }

    @Test
    public void write_400() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/write";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.write(DEFAULT_STORE_ID, new WriteRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void write_404() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/write";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.write(DEFAULT_STORE_ID, new WriteRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void write_500() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/write";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.write(DEFAULT_STORE_ID, new WriteRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Check whether a user is authorized to access an object.
     */
    @Test
    public void check() throws Exception {
        // Given
        String postPath = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/check";
        String expectedBody = String.format(
                "{\"tuple_key\":{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"},\"contextual_tuples\":{\"tuple_keys\":[]},\"authorization_model_id\":\"01G5JAVJ41T49E9TT3SKVS7X1J\",\"trace\":null}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER);
        mockHttpClient.onPost(postPath).withBody(is(expectedBody)).doReturn(200, "{\"allowed\":true}");
        CheckRequest request = new CheckRequest()
                .tupleKey(new TupleKey()
                        ._object(DEFAULT_OBJECT)
                        .relation(DEFAULT_RELATION)
                        .user(DEFAULT_USER))
                .contextualTuples(new ContextualTupleKeys())
                .authorizationModelId(DEFAULT_AUTH_MODEL_ID);

        // When
        CheckResponse response = fga.check(DEFAULT_STORE_ID, request);

        // Then
        verify(mockConfiguration).getApiUrl();
        verify(mockConfiguration).getReadTimeout();
        mockHttpClient.verify().post(postPath).withBody(is(expectedBody)).called(1);
        assertEquals(Boolean.TRUE, response.getAllowed());
    }

    @Test
    public void check_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.check(null, new CheckRequest()));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling check", exception.getMessage());
    }

    @Test
    public void check_bodyRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.check(DEFAULT_STORE_ID, null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling check", exception.getMessage());
    }

    @Test
    public void check_400() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/check";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.check(DEFAULT_STORE_ID, new CheckRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void check_404() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/check";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.check(DEFAULT_STORE_ID, new CheckRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void check_500() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/check";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.check(DEFAULT_STORE_ID, new CheckRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Expand all relationships in userset tree format, and following userset rewrite rules.  Useful to reason about and debug a certain relationship.
     */
    @Test
    public void expandTest() throws ApiException {
        // Given
        String postPath = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/expand";
        String expectedBody = String.format(
                "{\"tuple_key\":{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"},\"authorization_model_id\":\"%s\"}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER, DEFAULT_AUTH_MODEL_ID);
        String responseBody = String.format(
                "{\"tree\":{\"root\":{\"union\":{\"nodes\":[{\"leaf\":{\"users\":{\"users\":[\"%s\"]}}}]}}}}",
                DEFAULT_USER);
        mockHttpClient.onPost(postPath).withBody(is(expectedBody)).doReturn(200, responseBody);
        ExpandRequest request = new ExpandRequest()
                .authorizationModelId(DEFAULT_AUTH_MODEL_ID)
                .tupleKey(new TupleKey()
                        ._object(DEFAULT_OBJECT)
                        .relation(DEFAULT_RELATION)
                        .user(DEFAULT_USER));

        // When
        ExpandResponse response = fga.expand(DEFAULT_STORE_ID, request);

        // Then
        mockHttpClient.verify().post(postPath).withBody(is(expectedBody)).called(1);
        assertNotNull(response.getTree());
        assertNotNull(response.getTree().getRoot());
        assertNotNull(response.getTree().getRoot().getUnion());
        assertNotNull(response.getTree().getRoot().getUnion().getNodes());
        assertEquals(1, response.getTree().getRoot().getUnion().getNodes().size());
        assertNotNull(response.getTree().getRoot().getUnion().getNodes().get(0));
        Node node = response.getTree().getRoot().getUnion().getNodes().get(0);
        assertNotNull(node.getLeaf());
        assertNotNull(node.getLeaf().getUsers());
        assertNotNull(node.getLeaf().getUsers().getUsers());
        assertEquals(1, node.getLeaf().getUsers().getUsers().size());
        assertEquals(DEFAULT_USER, node.getLeaf().getUsers().getUsers().get(0));
    }

    @Test
    public void expand_storeIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.expand(null, new ExpandRequest()));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling expand", exception.getMessage());
    }

    @Test
    public void expand_bodyRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.expand(DEFAULT_STORE_ID, null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling expand", exception.getMessage());
    }

    @Test
    public void expand_400() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/expand";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.expand(DEFAULT_STORE_ID, new ExpandRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void expand_404() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/expand";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.expand(DEFAULT_STORE_ID, new ExpandRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void expand_500() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/expand";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.expand(DEFAULT_STORE_ID, new ExpandRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * List all objects of the given type that the user has a relation with.
     */
    @Test
    public void listObjectsTest() throws ApiException {
        // Given
        String postPath = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/list-objects";
        String expectedBody = String.format(
                "{\"authorization_model_id\":\"%s\",\"type\":null,\"relation\":\"%s\",\"user\":\"%s\",\"contextual_tuples\":null}",
                DEFAULT_AUTH_MODEL_ID, DEFAULT_RELATION, DEFAULT_USER);
        mockHttpClient
                .onPost(postPath)
                .withBody(is(expectedBody))
                .doReturn(200, String.format("{\"objects\":[\"%s\"]}", DEFAULT_OBJECT));
        ListObjectsRequest request = new ListObjectsRequest()
                .authorizationModelId(DEFAULT_AUTH_MODEL_ID)
                .relation(DEFAULT_RELATION)
                .user(DEFAULT_USER);

        // When
        ListObjectsResponse response = fga.listObjects(DEFAULT_STORE_ID, request);

        // Then
        mockHttpClient.verify().post(postPath).withBody(is(expectedBody)).called(1);
        assertEquals(List.of(DEFAULT_OBJECT), response.getObjects());
    }

    @Test
    public void listObjects_storeIdRequired() {
        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.listObjects(null, new ListObjectsRequest()));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling listObjects", exception.getMessage());
    }

    @Test
    public void listObjects_bodyRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.listObjects(DEFAULT_STORE_ID, null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling listObjects", exception.getMessage());
    }

    @Test
    public void listObjects_400() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/list-objects";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.listObjects(DEFAULT_STORE_ID, new ListObjectsRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void listObjects_404() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/list-objects";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.listObjects(DEFAULT_STORE_ID, new ListObjectsRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void listObjects_500() throws ApiException {
        // Given
        String postUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/list-objects";
        mockHttpClient
                .onPost(postUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.listObjects(DEFAULT_STORE_ID, new ListObjectsRequest()));

        // Then
        mockHttpClient.verify().post(postUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Read assertions for an authorization model ID.
     */
    @Test
    public void readAssertionsTest() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        String responseBody = String.format(
                "{\"assertions\":[{\"tuple_key\":{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"},\"expectation\":true}]}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER);
        mockHttpClient.onGet(getUrl).doReturn(200, responseBody);

        // When
        ReadAssertionsResponse response = fga.readAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID);

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertNotNull(response.getAssertions());
        assertEquals(1, response.getAssertions().size());
        Assertion assertion = response.getAssertions().get(0);
        assertNotNull(assertion);
        assertTrue(assertion.getExpectation());
        assertEquals(DEFAULT_OBJECT, assertion.getTupleKey().getObject());
        assertEquals(DEFAULT_RELATION, assertion.getTupleKey().getRelation());
        assertEquals(DEFAULT_USER, assertion.getTupleKey().getUser());
    }

    @Test
    public void readAssertions_storeIdRequired() {
        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.readAssertions(null, DEFAULT_AUTH_MODEL_ID));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling readAssertions", exception.getMessage());
    }

    @Test
    public void readAssertions_authModelIdRequired() {
        // When
        ApiException exception = assertThrows(ApiException.class, () -> fga.readAssertions(DEFAULT_STORE_ID, null));

        // Then
        assertEquals(
                "Missing the required parameter 'authorizationModelId' when calling readAssertions",
                exception.getMessage());
    }

    @Test
    public void readAssertions_400() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.readAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void readAssertions_404() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.readAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void readAssertions_500() throws ApiException {
        // Given
        String getUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onGet(getUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception =
                assertThrows(ApiException.class, () -> fga.readAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID));

        // Then
        mockHttpClient.verify().get(getUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }

    /**
     * Upsert assertions for an authorization model ID.
     */
    @Test
    public void writeAssertionsTest() throws ApiException {
        // Given
        String putUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        String expectedBody = String.format(
                "{\"assertions\":[{\"tuple_key\":{\"object\":\"%s\",\"relation\":\"%s\",\"user\":\"%s\"},\"expectation\":true}]}",
                DEFAULT_OBJECT, DEFAULT_RELATION, DEFAULT_USER);
        mockHttpClient.onPut(putUrl).withBody(is(expectedBody)).doReturn(200, EMPTY_RESPONSE_BODY);
        WriteAssertionsRequest request = new WriteAssertionsRequest()
                .assertions(List.of(new Assertion()
                        .tupleKey(new TupleKey()
                                ._object(DEFAULT_OBJECT)
                                .relation(DEFAULT_RELATION)
                                .user(DEFAULT_USER))
                        .expectation(true)));

        // When
        fga.writeAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID, request);

        // Then
        mockHttpClient.verify().put(putUrl).withBody(is(expectedBody)).called(1);
    }

    @Test
    public void writeAssertions_storeIdRequired() {
        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAssertions(null, DEFAULT_AUTH_MODEL_ID, new WriteAssertionsRequest()));

        // Then
        assertEquals("Missing the required parameter 'storeId' when calling writeAssertions", exception.getMessage());
    }

    @Test
    public void writeAssertions_authModelIdRequired() {
        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.writeAssertions(DEFAULT_STORE_ID, null, new WriteAssertionsRequest()));

        // Then
        assertEquals(
                "Missing the required parameter 'authorizationModelId' when calling writeAssertions",
                exception.getMessage());
    }

    @Test
    public void writeAssertions_bodyRequired() {
        // When
        ApiException exception = assertThrows(
                ApiException.class, () -> fga.writeAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID, null));

        // Then
        assertEquals("Missing the required parameter 'body' when calling writeAssertions", exception.getMessage());
    }

    @Test
    public void writeAssertions_400() throws ApiException {
        // Given
        String putUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onPut(putUrl)
                .doReturn(400, "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID, new WriteAssertionsRequest()));

        // Then
        mockHttpClient.verify().put(putUrl).called(1);
        assertEquals(400, exception.getCode());
        assertEquals(
                "{\"code\":\"validation_error\",\"message\":\"Generic validation error\"}",
                exception.getResponseBody());
    }

    @Test
    public void writeAssertions_404() throws ApiException {
        // Given
        String putUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onPut(putUrl)
                .doReturn(404, "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID, new WriteAssertionsRequest()));

        // Then
        mockHttpClient.verify().put(putUrl).called(1);
        assertEquals(404, exception.getCode());
        assertEquals(
                "{\"code\":\"undefined_endpoint\",\"message\":\"Endpoint not enabled\"}", exception.getResponseBody());
    }

    @Test
    public void writeAssertions_500() throws ApiException {
        // Given
        String putUrl = "https://localhost/stores/01YCP46JKYM8FJCQ37NMBYHE5X/assertions/01G5JAVJ41T49E9TT3SKVS7X1J";
        mockHttpClient
                .onPut(putUrl)
                .doReturn(500, "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}");

        // When
        ApiException exception = assertThrows(
                ApiException.class,
                () -> fga.writeAssertions(DEFAULT_STORE_ID, DEFAULT_AUTH_MODEL_ID, new WriteAssertionsRequest()));

        // Then
        mockHttpClient.verify().put(putUrl).called(1);
        assertEquals(500, exception.getCode());
        assertEquals(
                "{\"code\":\"internal_error\",\"message\":\"Internal Server Error\"}", exception.getResponseBody());
    }
}
