/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.client;

import dev.openfga.sdk.api.model.TupleKey;
import java.util.List;

public class ClientWriteRequest {
    private List<TupleKey> writes;
    private List<TupleKey> deletes;

    public ClientWriteRequest writes(List<TupleKey> writes) {
        this.writes = writes;
        return this;
    }

    public List<TupleKey> getWrites() {
        return writes;
    }

    public ClientWriteRequest deletes(List<TupleKey> deletes) {
        this.deletes = deletes;
        return this;
    }

    public List<TupleKey> getDeletes() {
        return deletes;
    }
}
