/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.client;

import dev.openfga.sdk.api.model.RelationshipCondition;

public class ClientRelationshipCondition {
    private String name;
    private Object context;

    public ClientRelationshipCondition name(String name) {
        this.name = name;
        return this;
    }

    public String getName() {
        return name;
    }

    public ClientRelationshipCondition context(Object context) {
        this.context = context;
        return this;
    }

    public Object getContext() {
        return context;
    }

    public RelationshipCondition asRelationshipCondition() {
        return new RelationshipCondition().name(name).context(context);
    }
}
