/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.telemetry;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class HistogramsTest {
    @Test
    void shouldCreateRequestDurationHistogram() {
        // given
        String expectedName = "fga-client.request.duration";
        String expectedDescription =
                "The total time (in milliseconds) it took for the request to complete, including the time it took to send the request and receive the response.";

        // when
        Histogram histogram = Histograms.REQUEST_DURATION;

        // then
        assertThat(histogram.getName()).isEqualTo(expectedName);
        assertThat(histogram.getUnit()).isEqualTo("milliseconds");
        assertThat(histogram.getDescription()).isEqualTo(expectedDescription);
    }

    @Test
    void shouldCreateQueryDurationHistogram() {
        // given
        String expectedName = "fga-client.query.duration";
        String expectedDescription =
                "The total time it took (in milliseconds) for the FGA server to process and evaluate the request.";

        // when
        Histogram histogram = Histograms.QUERY_DURATION;

        // then
        assertThat(histogram.getName()).isEqualTo(expectedName);
        assertThat(histogram.getUnit()).isEqualTo("milliseconds");
        assertThat(histogram.getDescription()).isEqualTo(expectedDescription);
    }
}
