/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Computed
 */
@JsonPropertyOrder({Computed.JSON_PROPERTY_USERSET})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2023-08-23T20:06:14.249201Z[Etc/UTC]")
public class Computed {
    public static final String JSON_PROPERTY_USERSET = "userset";
    private String userset;

    public Computed() {}

    public Computed userset(String userset) {
        this.userset = userset;
        return this;
    }

    /**
     * Get userset
     * @return userset
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_USERSET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getUserset() {
        return userset;
    }

    @JsonProperty(JSON_PROPERTY_USERSET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserset(String userset) {
        this.userset = userset;
    }

    /**
     * Return true if this Computed object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Computed computed = (Computed) o;
        return Objects.equals(this.userset, computed.userset);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userset);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Computed {\n");
        sb.append("    userset: ").append(toIndentedString(userset)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `userset` to the URL query string
        if (getUserset() != null) {
            joiner.add(String.format(
                    "%suserset%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getUserset()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
