/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * StreamResultOfStreamedListObjectsResponse
 */
@JsonPropertyOrder({
    StreamResultOfStreamedListObjectsResponse.JSON_PROPERTY_RESULT,
    StreamResultOfStreamedListObjectsResponse.JSON_PROPERTY_ERROR
})
public class StreamResultOfStreamedListObjectsResponse {
    public static final String JSON_PROPERTY_RESULT = "result";
    private StreamedListObjectsResponse result;

    public static final String JSON_PROPERTY_ERROR = "error";
    private Status error;

    public StreamResultOfStreamedListObjectsResponse() {}

    public StreamResultOfStreamedListObjectsResponse result(StreamedListObjectsResponse result) {
        this.result = result;
        return this;
    }

    /**
     * Get result
     * @return result
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RESULT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public StreamedListObjectsResponse getResult() {
        return result;
    }

    @JsonProperty(JSON_PROPERTY_RESULT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResult(StreamedListObjectsResponse result) {
        this.result = result;
    }

    public StreamResultOfStreamedListObjectsResponse error(Status error) {
        this.error = error;
        return this;
    }

    /**
     * Get error
     * @return error
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ERROR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Status getError() {
        return error;
    }

    @JsonProperty(JSON_PROPERTY_ERROR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setError(Status error) {
        this.error = error;
    }

    /**
     * Return true if this Stream_result_of_StreamedListObjectsResponse object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StreamResultOfStreamedListObjectsResponse streamResultOfStreamedListObjectsResponse =
                (StreamResultOfStreamedListObjectsResponse) o;
        return Objects.equals(this.result, streamResultOfStreamedListObjectsResponse.result)
                && Objects.equals(this.error, streamResultOfStreamedListObjectsResponse.error);
    }

    @Override
    public int hashCode() {
        return Objects.hash(result, error);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class StreamResultOfStreamedListObjectsResponse {\n");
        sb.append("    result: ").append(toIndentedString(result)).append("\n");
        sb.append("    error: ").append(toIndentedString(error)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `result` to the URL query string
        if (getResult() != null) {
            joiner.add(getResult().toUrlQueryString(prefix + "result" + suffix));
        }

        // add `error` to the URL query string
        if (getError() != null) {
            joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
        }

        return joiner.toString();
    }
}
