/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Usersets
 */
@JsonPropertyOrder({Usersets.JSON_PROPERTY_CHILD})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2023-08-21T20:03:24.252549Z[Etc/UTC]")
public class Usersets {
    public static final String JSON_PROPERTY_CHILD = "child";
    private List<Userset> child = new ArrayList<>();

    public Usersets() {}

    public Usersets child(List<Userset> child) {
        this.child = child;
        return this;
    }

    public Usersets addChildItem(Userset childItem) {
        if (this.child == null) {
            this.child = new ArrayList<>();
        }
        this.child.add(childItem);
        return this;
    }

    /**
     * Get child
     * @return child
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CHILD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<Userset> getChild() {
        return child;
    }

    @JsonProperty(JSON_PROPERTY_CHILD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setChild(List<Userset> child) {
        this.child = child;
    }

    /**
     * Return true if this Usersets object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Usersets usersets = (Usersets) o;
        return Objects.equals(this.child, usersets.child);
    }

    @Override
    public int hashCode() {
        return Objects.hash(child);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Usersets {\n");
        sb.append("    child: ").append(toIndentedString(child)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `child` to the URL query string
        if (getChild() != null) {
            for (int i = 0; i < getChild().size(); i++) {
                if (getChild().get(i) != null) {
                    joiner.add(getChild()
                            .get(i)
                            .toUrlQueryString(String.format(
                                    "%schild%s%s",
                                    prefix,
                                    suffix,
                                    "".equals(suffix)
                                            ? ""
                                            : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
                }
            }
        }

        return joiner.toString();
    }
}
