/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateStoreRequest
 */
public class CreateStoreRequestTest {
    private final CreateStoreRequest model = new CreateStoreRequest();

    /**
     * Model tests for CreateStoreRequest
     */
    @Test
    public void testCreateStoreRequest() {
        // TODO: test CreateStoreRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }
}
