/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ListObjectsResponse
 */
public class ListObjectsResponseTest {
    private final ListObjectsResponse model = new ListObjectsResponse();

    /**
     * Model tests for ListObjectsResponse
     */
    @Test
    public void testListObjectsResponse() {
        // TODO: test ListObjectsResponse
    }

    /**
     * Test the property 'objects'
     */
    @Test
    public void objectsTest() {
        // TODO: test objects
    }
}
