/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ListStoresResponse
 */
public class ListStoresResponseTest {
    private final ListStoresResponse model = new ListStoresResponse();

    /**
     * Model tests for ListStoresResponse
     */
    @Test
    public void testListStoresResponse() {
        // TODO: test ListStoresResponse
    }

    /**
     * Test the property 'stores'
     */
    @Test
    public void storesTest() {
        // TODO: test stores
    }

    /**
     * Test the property 'continuationToken'
     */
    @Test
    public void continuationTokenTest() {
        // TODO: test continuationToken
    }
}
