/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ReadChangesResponse
 */
public class ReadChangesResponseTest {
    private final ReadChangesResponse model = new ReadChangesResponse();

    /**
     * Model tests for ReadChangesResponse
     */
    @Test
    public void testReadChangesResponse() {
        // TODO: test ReadChangesResponse
    }

    /**
     * Test the property 'changes'
     */
    @Test
    public void changesTest() {
        // TODO: test changes
    }

    /**
     * Test the property 'continuationToken'
     */
    @Test
    public void continuationTokenTest() {
        // TODO: test continuationToken
    }
}
