/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TypeDefinition
 */
public class TypeDefinitionTest {
    private final TypeDefinition model = new TypeDefinition();

    /**
     * Model tests for TypeDefinition
     */
    @Test
    public void testTypeDefinition() {
        // TODO: test TypeDefinition
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'relations'
     */
    @Test
    public void relationsTest() {
        // TODO: test relations
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }
}
