/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Usersets
 */
public class UsersetsTest {
    private final Usersets model = new Usersets();

    /**
     * Model tests for Usersets
     */
    @Test
    public void testUsersets() {
        // TODO: test Usersets
    }

    /**
     * Test the property 'child'
     */
    @Test
    public void childTest() {
        // TODO: test child
    }
}
