/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.api.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for WriteRequest
 */
public class WriteRequestTest {
    private final WriteRequest model = new WriteRequest();

    /**
     * Model tests for WriteRequest
     */
    @Test
    public void testWriteRequest() {
        // TODO: test WriteRequest
    }

    /**
     * Test the property 'writes'
     */
    @Test
    public void writesTest() {
        // TODO: test writes
    }

    /**
     * Test the property 'deletes'
     */
    @Test
    public void deletesTest() {
        // TODO: test deletes
    }

    /**
     * Test the property 'authorizationModelId'
     */
    @Test
    public void authorizationModelIdTest() {
        // TODO: test authorizationModelId
    }
}
