/*
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.openfga.sdk.api.configuration;

import java.time.Duration;

public interface BaseConfiguration {
    String getApiUrl();

    String getUserAgent();

    Duration getReadTimeout();

    Duration getConnectTimeout();

    Integer getMaxRetries();

    Duration getMinimumRetryDelay();
}
